export class ProfileModel{
    constructor(
        public firstname : String,
        public lastname : String,
        public gender : String,
        public birthday : Date,
        public phonenumber : Number,
        public email : String,
        public address : String,
        public state : String,
        public institute1 : String,
        public course1 : String,
        public stream1 : String,
        public score1 : String,
        public passout1 : String,
        public institute2 : String,
        public course2 : String,
        public stream2 : String,
        public score2 : String,
        public passout2 : String,
        public institute3 : String,
        public score3 : String,
        public passout3 : String,
        public institute4 : String,
        public stream4 : String,
        public score4 : String,
        public passout4 : String,
        public training : String,
        public organization : String,
        public duration : String,
        public description : String,
        public skills : String,
        public resume : String,
        public coverletter : String,
        public photo : String,
        public link : String
    ){}
}